spring.application.name=MayaFisioLumiere
server.port=8081


spring.datasource.url=jdbc:postgresql://dpg-d6u4usea2pns739650fg-a.oregon-postgres.render.com/mayafisiolumiere_l6es?sslmode=require
spring.datasource.username=mayafisiolumiere_l6es_user
spring.datasource.password=vfz6XpEDrhaKRdOxBLO4dAvEBQgnt4Al


# JWT Configuration
api.security.token.secret=${JWT_SECRET:mayaLumiereFisio748546546}






# JAVA JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true




spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-test-query=SELECT 1
