spring.application.name=MayaFisioLumiere

spring.security.user.name=adminAna
spring.security.user.password=1234
spring.datasource.url=jdbc:postgresql://localhost:5432/lumiereAnaliceTeste
spring.datasource.username=postgres
spring.datasource.password=vivi1910
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-test-query=SELECT 1

